# Generated by Django 4.2.3 on 2023-07-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_is_admin_usermodel_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superadmin',
        ),
    ]
